var iPage={pageNo:0,pageSize:30,exportTip:"\u5168\u90e8\u5bfc\u51fa\u53ef\u80fd\u8017\u65f6\u8f83\u957f\uff0c\u786e\u5b9a\u5bfc\u51fa\uff1f",downloadAction:"export_download.action?data=",exportUrl:"export_select_info.action",exportAllUrl:"export_all_info.action",exportItem:".export_info",scrollToLoadRate:1,range:3,wait:1E3,mvItem:".item",colWidth:226,colDist:15,pageData:".page_data",content_html:"<div class='content_div'></div>",cache_html:"<div class='cache_div' style='display:none;'></div>",status_tip_html:"<div class='status_tip' style='cursor:pointer;text-align:center;margin-top:10px;'></div>",
gotop_html:"<div style='display:none;' id='gotopbtn' class='to_top'><a title='\u8fd4\u56de\u9876\u90e8' href='javascript:void(0);'></a></div>",page_foot_html:'<div class="page_info ipage-fenye"><div class="oper_div ipage-fenye-oper"><div class="select_div" style="float:left;margin-right:10px;"><input type="checkbox" class="select_all"/><span class="select_all_text">\u5168\u9009</span></div><div class="oper_btn_div" style="float:left;"></div></div><div class="ipage-fenye-btn"><button class="startPage page_btn ipage-fenye-on">\u9996\u9875</button><button class="prePage page_btn ipage-fenye-on">\u4e0a\u9875</button><button class="nextPage page_btn ipage-fenye-on">\u4e0b\u9875</button><button class="endPage page_btn ipage-fenye-on" style="display:none;">\u5c3e\u9875</button><input class="pageNo_input" type="text" value="1"/><button class="ipage-fenye-on go_btn">GO</button></div><div class="ipage-fenye-info">\u4fe1\u606f\u603b\u6570\uff1a<span class="ipage-number total"></span>&nbsp;&nbsp;\u603b\u9875\u6570\uff1a<span class="ipage-number totalPage"></span>&nbsp;&nbsp;\u5f53\u524d\u9875\uff1a<span class="ipage-number pageNo"></span></div></div>',
operBtnHtml:'<button class="ipage-fenye-on exoprt_btn">\u5bfc\u51fa\u6240\u9009</button>&nbsp;&nbsp;<button class="ipage-fenye-on exoprt_all_btn">\u5bfc\u51fa\u5168\u90e8</button>',container_foot_html:'<div class="page_info ipage-fenye"><div class="oper_div ipage-fenye-oper"><div class="select_div" style="float:left;margin-right:10px;"><input type="checkbox" class="select_all"/><span class="select_all_text">\u5168\u9009</span></div><div class="oper_btn_div" style="float:left;"></div></div></div>',
end_html:"<div class='page_end' >\u6682\u65e0\u6570\u636e</div>",loading_html:"<div style='line-height:80px;'><span class='page_loading'></span>\u6b63\u5728\u52aa\u529b\u52a0\u8f7d...</div>",more_html:"<div class='page_more'>\u52a0\u8f7d\u66f4\u591a</div>",ScrollLoadContainer:function(a,c,b){this.container=$("#"+a);this.url=c;this.param=b&&b.param?b.param:null;this.callback=b&&b.callback?b.callback:null;this.pageNo=b&&b.pageNo?b.pageNo:iPage.pageNo;this.pageSize=b&&b.pageSize?b.pageSize:iPage.pageSize;
this.range=b&&b.range?b.range:iPage.range;this.wait=b&&b.wait?b.wait:iPage.wait;this.scrollToLoadRate=b&&b.scrollToLoadRate?b.scrollToLoadRate:iPage.scrollToLoadRate;this.mvItem=b&&b.mvItem?b.mvItem:iPage.mvItem;this.exportHead=b&&b.exportHead?b.exportHead:null;this.exportUrl=b&&b.exportUrl?b.exportUrl:iPage.exportUrl;this.exportAllUrl=b&&b.exportAllUrl?b.exportAllUrl:iPage.exportAllUrl;this.exportItem=b&&b.exportItem?b.exportItem:iPage.exportItem;this.operBtnBind=b&&b.operBtnBind?b.operBtnBind:void 0;
this.operBtnHtml=b&&b.operBtnHtml?b.operBtnHtml:iPage.operBtnHtml;this.count;this.isRec=1;this.handle=null;this.isFirstLoad=!0;this.$pageInfo;this.$contentDiv;this.$operDiv},ScrollLoadWindow:function(a,c,b){this.container=$("#"+a);this.url=c;this.param=b&&b.param?b.param:null;this.callback=b&&b.callback?b.callback:null;this.pageNo=b&&b.pageNo?b.pageNo:iPage.pageNo;this.pageSize=b&&b.pageSize?b.pageSize:iPage.pageSize;this.range=b&&b.range?b.range:iPage.range;this.wait=b&&b.wait?b.wait:iPage.wait;
this.scrollToLoadRate=b&&b.scrollToLoadRate?b.scrollToLoadRate:iPage.scrollToLoadRate;this.mvItem=b&&b.mvItem?b.mvItem:iPage.mvItem;this.count;this.isRec=1;this.handle=null;this.isFirstLoad=!0},ScrollLoadWindowMasonry:function(a,c,b){this.container=$("#"+a);this.url=c;this.param=b&&b.param?b.param:null;this.callback=b&&b.callback?b.callback:null;this.pageNo=b&&b.pageNo?b.pageNo:iPage.pageNo;this.pageSize=b&&b.pageSize?b.pageSize:iPage.pageSize;this.range=b&&b.range?b.range:iPage.range;this.wait=b&&
b.wait?b.wait:iPage.wait;this.scrollToLoadRate=b&&b.scrollToLoadRate?b.scrollToLoadRate:iPage.scrollToLoadRate;this.mvItem=b&&b.mvItem?b.mvItem:iPage.mvItem;this.colWidth=b&&b.colWidth?b.colWidth:iPage.colWidth;this.colDist=b&&b.colDist?b.colDist:iPage.colDist;this.count;this.isRec=1;this.handle=null;this.isFirstLoad=!0},PageLoad:function(a,c,b){this.container=$("#"+a);this.url=c;this.param=b&&b.param?b.param:null;this.callback=b&&b.callback?b.callback:null;this.pageNo=b&&b.pageNo?b.pageNo:iPage.pageNo;
this.pageSize=b&&b.pageSize?b.pageSize:iPage.pageSize;this.pageData=b&&b.pageData?b.pageData:iPage.pageData;this.exportHead=b&&b.exportHead?b.exportHead:null;this.exportUrl=b&&b.exportUrl?b.exportUrl:iPage.exportUrl;this.exportAllUrl=b&&b.exportAllUrl?b.exportAllUrl:iPage.exportAllUrl;this.exportItem=b&&b.exportItem?b.exportItem:iPage.exportItem;this.operBtnBind=b&&b.operBtnBind?b.operBtnBind:void 0;this.operBtnHtml=b&&b.operBtnHtml?b.operBtnHtml:iPage.operBtnHtml;this.count;this.isRec=1;this.total=
-1;this.totalPage;this.$pageInfo;this.$contentDiv;this.$operDiv}};
iPage.ScrollLoadContainer.prototype.init=function(){var a=this;return a.container.empty(),a.container.next(".page_info").remove(),a.container.append(iPage.content_html),a.container.append(iPage.cache_html),a.container.append(iPage.status_tip_html),a.container.after(iPage.container_foot_html),a.$pageInfo=a.container.next(".page_info"),a.$contentDiv=a.container.find(".content_div"),a.$operDiv=a.$pageInfo.find(".oper_div"),a.operBtnHtml?(a.$operDiv.find(".oper_btn_div").append(a.operBtnHtml),a.$pageInfo.find(".select_all").click(function(){$(this).is(":checked")?
a.$contentDiv.find(a.exportItem).attr("checked",!0):a.$contentDiv.find(a.exportItem).attr("checked",!1)}),a.$operDiv.find(".exoprt_btn").length&&a.$operDiv.find(".exoprt_btn").unbind("click").click(function(){if(a.exportHead&&a.exportUrl){var c=a.$contentDiv.find(a.exportItem+":checked");if(!c.length)return alert("\u8bf7\u9009\u62e9\u8bb0\u5f55!"),void 0;for(var b={},e=[],f=[],d=0;d<a.exportHead.length;d++)e.push(a.exportHead[d].n);c.each(function(b,c){var g=[];for(b=0;b<a.exportHead.length;b++)g.push($(c).data(a.exportHead[b].d));
f.push(g)});b.head=e;b.data=f;c=JSON.stringify(b);$.post(a.exportUrl,{data:c},function(a){"error"==a?alert("\u6682\u65e0\u6570\u636e!"):window.location.href=iPage.downloadAction+a})}}),a.$operDiv.find(".exoprt_all_btn").length&&a.$operDiv.find(".exoprt_all_btn").unbind("click").click(function(){if(confirm(iPage.exportTip)&&a.exportAllUrl){var c=a.exportAllUrl+(-1<a.url.indexOf("?")?a.url.substring(a.url.indexOf("?"),a.url.length):"");a.param?$.post(c,a.param,function(a){"error"==a?alert("\u6682\u65e0\u6570\u636e!"):
window.location.href=iPage.downloadAction+a}):$.get(c,function(a){"error"==a?alert("\u6682\u65e0\u6570\u636e!"):window.location.href=iPage.downloadAction+a})}}),a.operBtnBind&&a.operBtnBind()):a.$pageInfo.hide(),a.count=a.range,$(".status_tip",a.container).unbind("click").click(function(){2==a.isRec&&(a.count=a.range,a.loadMore())}),a.container.unbind("scroll").scroll(function(){clearTimeout(a.handle);a.container.scrollTop()+a.container.height()>=a.container.find(".content_div").height()*a.scrollToLoadRate&&
1==a.isRec&&(a.handle=setTimeout(function(){a.loadMore()},a.wait))}),a.loadMore(),a};iPage.ScrollLoadContainer.prototype.loadMore=function(){this.isRec=0;this.count--;this.pageNo++;this.updateTip();this.loadPage()};
iPage.ScrollLoadContainer.prototype.updateTip=function(){switch(this.isRec){case -1:$(".status_tip",this.container).html(iPage.end_html);break;case 0:$(".status_tip",this.container).html(iPage.loading_html);break;case 1:$(".status_tip",this.container).html("");break;case 2:$(".status_tip",this.container).html(iPage.more_html)}};
iPage.ScrollLoadContainer.prototype.loadPage=function(){var a=this;console.log("loadPage");var c=-1<a.url.indexOf("?")?"&":"?";c+="pageNo="+a.pageNo+"&pageSize="+a.pageSize;a.param?$(".cache_div",a.container).load(a.url+c,a.param,function(){a.loadPageAfter()}):$(".cache_div",a.container).load(a.url+c,function(){a.loadPageAfter()})};
iPage.ScrollLoadContainer.prototype.loadPageAfter=function(){this.callback&&this.callback($(".cache_div",this.container));var a=$(".cache_div",this.container).find(this.mvItem);null!=a&&0<a.length?(this.isFirstLoad?($(".content_div",this.container).append(a),this.isFirstLoad=!1):(a.hide(),$(".content_div",this.container).append(a),a.fadeIn()),this.isRec=0==this.count?2:1,$(".cache_div",this.container).empty()):this.isRec=-1;this.updateTip()};
iPage.ScrollLoadWindow.prototype.init=function(){var a=this;return a.container.empty(),a.container.append(iPage.content_html),a.container.append(iPage.cache_html),a.container.append(iPage.status_tip_html),a.container.append(iPage.gotop_html),a.count=a.range,$(".status_tip",a.container).click(function(){2==a.isRec&&(a.count=a.range,a.loadMore())}),$("#gotopbtn").click(function(){$(document).scrollTop(0)}),$(document).scroll(function(){$(document).scrollTop()>window.innerHeight?$("#gotopbtn").css("display",
""):$("#gotopbtn").css("display","none");clearTimeout(a.handle);$(document).scrollTop()+window.innerHeight>=(a.container.offset().top+a.container.find(".content_div").height())*a.scrollToLoadRate&&1==a.isRec&&(a.handle=setTimeout(function(){a.loadMore()},a.wait))}),a.loadMore(),a};iPage.ScrollLoadWindow.prototype.loadMore=function(){this.isRec=0;this.count--;this.pageNo++;this.updateTip();this.loadPage()};
iPage.ScrollLoadWindow.prototype.updateTip=function(){switch(this.isRec){case -1:$(".status_tip",this.container).html(this.end_html);break;case 0:$(".status_tip",this.container).html(this.loading_html);break;case 1:$(".status_tip",this.container).html("");break;case 2:$(".status_tip",this.container).html(this.more_html)}};
iPage.ScrollLoadWindow.prototype.loadPage=function(){var a=this;console.log("loadPage");-1==a.url.indexOf("?")&&(a.url+="?");a.url+="&pageNo="+a.pageNo+"&pageSize="+a.pageSize;a.param?$(".cache_div",a.container).load(a.url,a.param,function(){a.loadPageAfter()}):$(".cache_div",a.container).load(a.url,function(){a.loadPageAfter()})};
iPage.ScrollLoadWindow.prototype.loadPageAfter=function(){this.callback&&this.callback($(".cache_div",this.container));var a=$(".cache_div",this.container).find(this.mvItem);null!=a&&0<a.length?(this.isFirstLoad?($(".content_div",this.container).append(a),this.isFirstLoad=!1):(a.hide(),$(".content_div",this.container).append(a),a.fadeIn()),this.isRec=0==this.count?2:1,$(".cache_div",this.container).empty()):this.isRec=-1;this.updateTip()};
iPage.ScrollLoadWindowMasonry.prototype.init=function(){var a=this;return a.container.empty(),a.container.append(iPage.content_html),a.container.append(iPage.cache_html),a.container.append(iPage.status_tip_html),a.container.append(iPage.gotop_html),a.count=a.range,$(".status_tip",a.container).click(function(){2==a.isRec&&(a.count=a.range,a.loadMore())}),$("#gotopbtn").click(function(){$(document).scrollTop(0)}),$(document).scroll(function(){$(document).scrollTop()>window.innerHeight?$("#gotopbtn").css("display",
""):$("#gotopbtn").css("display","none");clearTimeout(a.handle);$(document).scrollTop()+window.innerHeight>=(a.container.offset().top+a.container.find(".content_div").height())*a.scrollToLoadRate&&1==a.isRec&&(a.handle=setTimeout(function(){a.loadMore()},a.wait))}),a.loadMore(),a};iPage.ScrollLoadWindowMasonry.prototype.loadMore=function(){this.isRec=0;this.count--;this.pageNo++;this.updateTip();this.loadPage()};
iPage.ScrollLoadWindowMasonry.prototype.updateTip=function(){switch(this.isRec){case -1:$(".status_tip",this.container).html(this.end_html);break;case 0:$(".status_tip",this.container).html(this.loading_html);break;case 1:$(".status_tip",this.container).html("");break;case 2:$(".status_tip",this.container).html(this.more_html)}};
iPage.ScrollLoadWindowMasonry.prototype.loadPage=function(){var a=this;console.log("loadPage");-1==a.url.indexOf("?")&&(a.url+="?");a.url+="&pageNo="+a.pageNo+"&pageSize="+a.pageSize;a.param?$(".cache_div",a.container).load(a.url,a.param,function(){a.loadPageAfter()}):$(".cache_div",a.container).load(a.url,function(){a.loadPageAfter()})};
iPage.ScrollLoadWindowMasonry.prototype.loadPageAfter=function(){var a=this;a.callback&&a.callback($(".cache_div",a.container));var c=$(".cache_div",a.container).find(a.mvItem);null!=c&&0<c.length?(a.isFirstLoad?($(".content_div",a.container).append(c),$(".content_div",a.container).imagesLoaded(function(){$(".content_div",a.container).masonry({itemSelector:a.mvItem,columnWidth:a.columnWidth,gutterWidth:a.gutterWidth})}),$(".content_div",a.container).masonry({itemSelector:a.mvItem,columnWidth:a.columnWidth,
gutterWidth:a.gutterWidth}),a.isFirstLoad=!1):(c.hide(),$(".content_div",a.container).append(c).masonry("reload"),c.fadeIn()),a.isRec=0==a.count?2:1,$(".cache_div",a.container).empty()):a.isRec=-1;a.updateTip()};
iPage.PageLoad.prototype.init=function(){var a=this;return a.container.empty(),a.container.append(iPage.content_html),a.container.append(iPage.page_foot_html),a.$pageInfo=a.container.find(".page_info"),a.$contentDiv=a.container.find(".content_div"),a.$operDiv=a.$pageInfo.find(".oper_div"),a.operBtnHtml?(a.$operDiv.find(".oper_btn_div").append(a.operBtnHtml),a.$pageInfo.find(".select_all").click(function(){$(this).is(":checked")?a.$contentDiv.find(a.exportItem).attr("checked",!0):a.$contentDiv.find(a.exportItem).attr("checked",
!1)}),a.$operDiv.find(".exoprt_btn").length&&a.$operDiv.find(".exoprt_btn").unbind("click").click(function(){if(a.exportHead&&a.exportUrl){var c=a.$contentDiv.find(a.exportItem+":checked");if(!c.length)return alert("\u8bf7\u9009\u62e9\u8bb0\u5f55!"),void 0;for(var b={},e=[],f=[],d=0;d<a.exportHead.length;d++)e.push(a.exportHead[d].n);c.each(function(b,c){var d=[];for(b=0;b<a.exportHead.length;b++)d.push($(c).data(a.exportHead[b].d));f.push(d)});b.head=e;b.data=f;c=JSON.stringify(b);$.post(a.exportUrl,
{data:c},function(a){"error"==a?alert("\u6682\u65e0\u6570\u636e!"):window.location.href=iPage.downloadAction+a})}}),a.$operDiv.find(".exoprt_all_btn").length&&a.$operDiv.find(".exoprt_all_btn").unbind("click").click(function(){if(confirm(iPage.exportTip)&&a.exportAllUrl){var c=a.exportAllUrl+(-1<a.url.indexOf("?")?a.url.substring(a.url.indexOf("?"),a.url.length):"");a.param?$.post(c,a.param,function(a){"error"==a?alert("\u6682\u65e0\u6570\u636e!"):window.location.href=iPage.downloadAction+a}):$.get(c,
function(a){"error"==a?alert("\u6682\u65e0\u6570\u636e!"):window.location.href=iPage.downloadAction+a})}}),a.operBtnBind&&a.operBtnBind()):a.$operDiv.hide(),a.$pageInfo.find(".go_btn").click(function(){if(1==a.isRec){var c=a.$pageInfo.find(".pageNo_input").val();c?(c=parseInt(c),0<c&&c<=a.totalPage?(a.pageNo=c,a.loadMore()):alert("\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u9875\u7801")):alert("\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u9875\u7801")}}),a.$pageInfo.find(".page_btn").unbind().click(function(){if(1==
a.isRec){var c=$(this).attr("pageNo");c&&(c=parseInt(c),a.pageNo=c,a.loadMore())}}),a.loadMore(),a};iPage.PageLoad.prototype.loadMore=function(){this.isRec=0;this.updateTip();this.loadPage()};iPage.PageLoad.prototype.updateTip=function(){switch(this.isRec){case 0:$(".content_div",this.container).html(iPage.status_tip_html).find(".status_tip").html(iPage.loading_html)}};
iPage.PageLoad.prototype.loadPage=function(){var a=this;console.log("loadPage");var c=-1<a.url.indexOf("?")?"&":"?";-1==a.total&&(c+="total="+a.total+"&",a.pageNo=1>a.pageNo?1:a.pageNo);c+="pageNo="+a.pageNo+"&pageSize="+a.pageSize;a.param?$(".content_div",a.container).load(a.url+c,a.param,function(){a.loadPageAfter()}):$(".content_div",a.container).load(a.url+c,function(){a.loadPageAfter()})};
iPage.PageLoad.prototype.loadPageAfter=function(){this.callback&&this.callback($(".content_div",this.container));-1==this.total&&(this.total=this.container.find(this.pageData).data("total"));this.totalPage||(this.totalPage=parseInt(this.total/this.pageSize)+(0<this.total%this.pageSize?1:0));this.$pageInfo.find(".total").html(this.total);this.$pageInfo.find(".totalPage").html(this.totalPage);this.$pageInfo.find(".pageNo").html(this.pageNo);this.$pageInfo.find(".startPage").attr("pageNo",1);this.$pageInfo.find(".endPage").attr("pageNo",
this.totalPage);this.$pageInfo.find(".pageNo_input").val(this.pageNo);1<this.pageNo?(this.$pageInfo.find(".prePage").removeAttr("disabled").removeClass("ipage-fenye-off").addClass("ipage-fenye-on").attr("pageNo",this.pageNo-1),this.$pageInfo.find(".startPage").removeAttr("disabled").removeClass("ipage-fenye-off").addClass("ipage-fenye-on")):(this.$pageInfo.find(".prePage").attr("disabled",!0).removeClass("ipage-fenye-on").addClass("ipage-fenye-off").attr("pageNo",1),this.$pageInfo.find(".startPage").attr("disabled",
!0).removeClass("ipage-fenye-on").addClass("ipage-fenye-off"));this.pageNo<this.totalPage?(this.$pageInfo.find(".nextPage").removeAttr("disabled").removeClass("ipage-fenye-off").addClass("ipage-fenye-on").attr("pageNo",parseInt(this.pageNo)+1),this.$pageInfo.find(".endPage").removeAttr("disabled").removeClass("ipage-fenye-off").addClass("ipage-fenye-on")):(this.$pageInfo.find(".nextPage").attr("disabled",!0).removeClass("ipage-fenye-on").addClass("ipage-fenye-off").attr("pageNo",this.totalPage),this.$pageInfo.find(".endPage").attr("disabled",
!0).removeClass("ipage-fenye-on").addClass("ipage-fenye-off"));this.isRec=1;this.updateTip()};